name: Auto-generate jobs and blogs index with robust parsing
permissions:
  contents: write
on:
  push:
    branches:
      - main
      - master
    paths:
      - "jobs/**"
      - "blogs/**"
      - ".github/workflows/generate-indexes.yml"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install BeautifulSoup
        run: python -m pip install --upgrade pip beautifulsoup4

      # Generate jobs/index.json using new script
      - name: Generate jobs-list.json
        run: python scripts/generate-jobs-list.py

      # Generate blogs-list.json using new script
      - name: Generate blogs-list.json
        run: python scripts/generate-blogs-list.py

      # Generate combined recent-posts.json by merging jobs and blogs JSON
      - name: Generate combined recent-posts.json
        run: |
          python - <<'PYTHON'
          import json
          import os

          with open('jobs/jobs-list.json', 'r', encoding='utf-8') as f:
              jobs = json.load(f)

          blogs_path = 'blogs/blogs-list.json'
          if os.path.exists(blogs_path):
              with open(blogs_path, 'r', encoding='utf-8') as f:
                  blogs = json.load(f)
          else:
              blogs = []

          combined = jobs + blogs
          combined.sort(key=lambda x: x.get('date') or '', reverse=True)

          recent = combined[:10]

          with open('recent-posts.json', 'w', encoding='utf-8') as f:
              json.dump(recent, f, ensure_ascii=False, indent=2)
          PYTHON

      # Commit and push generated JSON files
      - name: Commit and push JSON files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add jobs/jobs-list.json blogs/blogs-list.json recent-posts.json
          git commit -m 'auto: update jobs, blogs, and combined recent posts JSON' || echo 'No changes to commit'
          git push origin HEAD:${{ github.ref_name }}
