name: Generate Jobs Index

on:
  push:
    paths:
      - "jobs/*.html"
      - ".github/workflows/generate-jobs.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate jobs.json
        run: |
          echo "[" > jobs/jobs.json
          for file in jobs/*.html; do
            # skip index.html so it doesn't list itself
            if [ "$(basename "$file")" = "index.html" ]; then continue; fi
            title=$(grep -oP '(?<=<title>).*?(?=</title>)' "$file" | head -n 1)
            desc=$(grep -oP '(?<=<meta name="description" content=").*?(?=">)' "$file" | head -n 1)
            fname=$(basename "$file")
            echo "  {\"title\": \"$title\", \"description\": \"$desc\", \"link\": \"/jobs/$fname\", \"date\": \"$(date +%Y-%m-%d)\"}," >> jobs/jobs.json
          done
          sed -i '$ s/,$//' jobs/jobs.json
          echo "]" >> jobs/jobs.json

      - name: Commit and push jobs.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add jobs/jobs.json
          git commit -m "Update jobs.json" || echo "No changes to commit"
          git push
